### PR TITLE
count sort algorithms with Python3 #234

### PR DESCRIPTION
**Pull request by Animesht1008**
Count sort algorithms with Python3 and Also Implemented the basic Working of the count sort in python3.

### CODE REVIEW

**Comment by Knackie** [comment]
Thanks.
Could you please follow the issue #296 and make the template for PR ?
And could you update the readme ?
Also, the files is not in the good repository, count sort is in : ar-csrt
Thanks.

**Comment by Animesht1008** [comment]
okay I will do that

**Comment by Animesht1008** [comment]
@Knackie can i make a new pull request for the above as i am facing some issue

**Comment by Animesht1008** [comment]
@Knackie can i open a new pull request for the above implementation as i am facing some issue with the current one.

**Comment by Knackie** [comment]
> @Knackie can i open a new pull request for the above implementation as i am facing some issue with the current one.

yes sure

**Pull request closed without merging**
