### PR TITLE
Added Fenwick Tree in C++ for #362

### PR DESCRIPTION
**Pull request by sans-23**
Fenwick tree for range sum query and point update.
Please Merge this code.

### CODE REVIEW

**Comment by Knackie** [comment]
Hi, 
Could you update the readme reefer to #296

**Comment by sans-23** [comment]
yes sure

**Comment by sans-23** [comment]
I have updated the readme file now. Please review and merge it.

**Comment by Knackie** [comment]
There is some conflicts

**Comment by Knackie** [comment]
Thanks ! don't hesitate to leave a star⭐⭐⭐

**Pull request merged**
