### PR TITLE
Add merge sort in linked list

### PR DESCRIPTION
**Pull request by s4shantanu**
Hey bud,
I add the merge sort java solution this is working properly in the linked list repo.
Please Approve my PR.
I'm participating in hacktoberfest please approve my PR .
Thanks,
Shantanu

### CODE REVIEW

**Review by s4shantanu — COMMENTED** [review]
Code working properly.

**Comment by Knackie** [comment]
Can you update the readme

**Comment by s4shantanu** [comment]
> Can you update the readme

Oops, No I'm not updating the readme file can I update Now?

**Comment by s4shantanu** [comment]
Hi @Knackie Actually readme file is already update please check

**Comment by Knackie** [comment]
Thanks, don't hesitate to leave a star 🎇🎇🎇

**Comment by s4shantanu** [comment]
Please wait a second i also contribute my second contribution with heap sorting code and updated readme file

**Pull request merged**
