### PR TITLE
Added Insertion in LinkedList at Different Position in DSA Folder

### PR DESCRIPTION
**Pull request by iamakhileshmishra**
Please accept it under hacktoberfest-accepted

### CODE REVIEW

**Comment by Knackie** [comment]
Hi, 
Could you update the readme reefer to #296

**Comment by iamakhileshmishra** [comment]
Could you now check @Knackie

**Comment by Knackie** [comment]
Thanks ! don't hesitate to leave a star ⭐

**Comment by iamakhileshmishra** [comment]
Is this repo got excluded?? as my PR through this Reop got excluded from Hacktoberfest Count

**Pull request merged**
