### PR TITLE
Create queue_implement.cpp

### PR DESCRIPTION
**Pull request by CodeLalit007**

### CODE REVIEW

**Comment by Knackie** [comment]
Hi.
Please read the readme and #296 to make a great PR

**Comment by CodeLalit007** [comment]
> Hi. Please read the readme and #296 to make a great PR

Done

**Comment by Knackie** [comment]
You still haven't update the readme and make checkbox in PR

**Comment by CodeLalit007** [comment]
> You still haven't update the readme and make checkbox in PR

I have done it already, pls check

**Pull request closed without merging**
